from datetime import datetime

MARKET_1 = 'BTC'
MARKET_2 = 'USD'

START_TIME = datetime(2020, 4, 1)
END_TIME = datetime(2020, 5, 21)

PAST_DAYS_USED_TO_PREDICT = 7
DAYS_TO_PREDICT = 4

ITERATIONS = 100
MUTATION_WEIGHT = 0.6
